### ISSUE TITLE
As an operator I want to make adjustments to a promotion while it is enabled and in window

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#123]
Operators may need to make adjustments while a promo live, rather than needing to end the promotion and create a new one. Here's what an operator should be able to edit while promotion is enabled and in window:

- [ ] Inclusions and Exclusions on Triggers and Promotions - it's common for brands to reach out about MAP violations or to request certain items be excluded from an active promo
- [ ] End date - Operators will want to be able to extend a promotion without interruption
- [ ] Promotion Name - Operator may want to change the internal name of the promo while it is live

**Comment by brent-hoover** [comment]
@brendan-shea-pm a little concerned about the change of inclusions and exclusions since you can almost entirely change the way the promotion operates. Can we narrow it down and say you can **add** exclusions only and that we can track that change with a history? I can see this causing serious problems if you try to audit a promotion and the terms have changed.

**Comment by brendan-shea-pm** [comment]
I will run that by Rick, seems to me that only adding exclusions (rather then adding inclusions) would be ok.

**Comment by brent-hoover** [comment]
@brendan-shea-pm pinging this as I want to add the restrictions on editing an active promotion before we go live.
